// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjUh9gXnHYMdThneTr8g_G0DJLxlpAmJM',
    appId: '1:134395559709:web:d0477e0350693050ababf4',
    messagingSenderId: '134395559709',
    projectId: 'flutter-bedulgarage',
    authDomain: 'flutter-bedulgarage.firebaseapp.com',
    storageBucket: 'flutter-bedulgarage.firebasestorage.app',
    measurementId: 'G-73SV2GG1PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPxyRSoAlEIv4_6ahzyD6yp1aQ_APFR8s',
    appId: '1:134395559709:android:af8b91e372799f8cababf4',
    messagingSenderId: '134395559709',
    projectId: 'flutter-bedulgarage',
    storageBucket: 'flutter-bedulgarage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWqDLmg2B8mCQB0RZmAM_VS-AURrMDBTU',
    appId: '1:134395559709:ios:02054116644a6882ababf4',
    messagingSenderId: '134395559709',
    projectId: 'flutter-bedulgarage',
    storageBucket: 'flutter-bedulgarage.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWqDLmg2B8mCQB0RZmAM_VS-AURrMDBTU',
    appId: '1:134395559709:ios:02054116644a6882ababf4',
    messagingSenderId: '134395559709',
    projectId: 'flutter-bedulgarage',
    storageBucket: 'flutter-bedulgarage.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjUh9gXnHYMdThneTr8g_G0DJLxlpAmJM',
    appId: '1:134395559709:web:37bbeaa169d22228ababf4',
    messagingSenderId: '134395559709',
    projectId: 'flutter-bedulgarage',
    authDomain: 'flutter-bedulgarage.firebaseapp.com',
    storageBucket: 'flutter-bedulgarage.firebasestorage.app',
    measurementId: 'G-NEJLMM2HH9',
  );
}
