// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbM49TwihnwlHK9Il4axEnxnmhnf5B_p8',
    appId: '1:151838579509:web:50900fd85702cc415e0a7c',
    messagingSenderId: '151838579509',
    projectId: 'fir-flutter-d1590',
    authDomain: 'fir-flutter-d1590.firebaseapp.com',
    storageBucket: 'fir-flutter-d1590.firebasestorage.app',
    measurementId: 'G-JQH0H29Q4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDwzy4JRqtVpaVk_wqiEroaDEZqmaD7wQ',
    appId: '1:151838579509:android:c815a2f2090dcb605e0a7c',
    messagingSenderId: '151838579509',
    projectId: 'fir-flutter-d1590',
    storageBucket: 'fir-flutter-d1590.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwOVKvIov6-jnfyaxZjJwuj-of8Jt4644',
    appId: '1:151838579509:ios:1ed86e3a827649975e0a7c',
    messagingSenderId: '151838579509',
    projectId: 'fir-flutter-d1590',
    storageBucket: 'fir-flutter-d1590.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwOVKvIov6-jnfyaxZjJwuj-of8Jt4644',
    appId: '1:151838579509:ios:1ed86e3a827649975e0a7c',
    messagingSenderId: '151838579509',
    projectId: 'fir-flutter-d1590',
    storageBucket: 'fir-flutter-d1590.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbM49TwihnwlHK9Il4axEnxnmhnf5B_p8',
    appId: '1:151838579509:web:b77fc22e5f5f41185e0a7c',
    messagingSenderId: '151838579509',
    projectId: 'fir-flutter-d1590',
    authDomain: 'fir-flutter-d1590.firebaseapp.com',
    storageBucket: 'fir-flutter-d1590.firebasestorage.app',
    measurementId: 'G-H0FKPHEK08',
  );
}
